# Generated by Django 4.0.2 on 2022-02-22 17:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import meeting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=500)),
                ('dateScheduled', models.DateTimeField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True, validators=[meeting.models.validate_date])),
                ('slug', models.SlugField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['-dateScheduled'],
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meeting.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=30)),
                ('doc', models.FileField(max_length=50, upload_to='documents')),
                ('dateuploaded', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meeting.meeting')),
            ],
            options={
                'ordering': ['-dateuploaded'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='meeting.meeting')),
            ],
            options={
                'ordering': ['-dateCreated'],
            },
        ),
    ]
