# Generated by Django 4.0.2 on 2022-02-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='success',
        ),
    ]
