# Generated by Django 4.0.2 on 2022-02-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-dateCreated']},
        ),
    ]
